[client]
toolbarMode = "viewer"
showErrorDetails = false

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#6366F1"
backgroundColor = "#1B1F2E"
secondaryBackgroundColor = "#2C3252"
textColor = "#F1F5F9"
font = "sans serif"
